Repository Marcelo-Diament/colearning-20220409, pull requests merged in 2022-04, with the labels that each got.

#1 doc: Incluindo enunciados e responsáveis
  README.md
Labels: documentation, good first issue

#3 feat: Criando Pojeto node Dependencias e iscripts
  package-lock.json
  package.json
Labels: enhancement

#4 Feature/config servidor node html
  index.js
  package-lock.json
Labels: enhancement, good first issue

#5 Feature/criando arquivo html
  views/index.html
  views/sobre.html
Labels: enhancement

#2 Pasta views e arquivo index.html criados :D
  views/index.html
Labels: documentation, enhancement
